### ISSUE TITLE
Why broadcast to Sink.ignore

### ISSUE THREAD

**Issue by kra3** [rocketpages/flight_delay_akka_streams#4]
@rocketpages would you please help me understand why there is a broadcast to `Sink.ignore`
Can't the flow be just `A ~> B ~> C ~> F ~> G` ?

I tried to look elsewhere in the web but found no reference to such a requirement. 
Any pointers are hugely appreciated. :sos:

**Comment by rocketpages** [comment]
Sorry for the long delay in answering this. 

There is no requirement to broadcast to Sink.ignore, it was only a demonstration to show a fan-out operation based on the article https://medium.com/@kvnwbbr/diving-into-akka-streams-2770b3aeabb0

The only requirement is that to materialize and run a flow, all outlets need to be connected to some type of sink, which is why I used Sink.ignore.
